backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"      # 실제 업로드 저장 위치
public_folder: "/assets/uploads"    # 웹 경로

publish_mode: editorial_workflow     # 초안-검토-발행(원하면 simple 로 바꿔도 됨)
locale: "ko"

collections:
  - name: "site"
    label: "사이트 내용"
    files:
      - name: "홈/Hero"
        label: "홈(Hero)"
        file: "site.json"
        fields:
          - { label: "Hero 제목(HTML 허용)", name: "hero.title", widget: "text" }
          - { label: "Hero 서브(HTML 허용)", name: "hero.sub", widget: "text" }
          - { label: "About 개요", name: "about.overview", widget: "text" }
          - { label: "연혁 1", name: "about.history1", widget: "string" }
          - { label: "연혁 2", name: "about.history2", widget: "string" }
          - { label: "서비스-Printing", name: "services.print", widget: "text" }
          - { label: "서비스-Brand", name: "services.brand", widget: "text" }
          - { label: "서비스-Creative", name: "services.creative", widget: "text" }
          - { label: "DTF 항목", name: "tech.dtf", widget: "list", field: {label: "문장", name: "item", widget: "string"} }
          - { label: "HTV 항목", name: "tech.htv", widget: "list", field: {label: "문장", name: "item", widget: "string"} }
          - { label: "Sublimation 항목", name: "tech.sub", widget: "list", field: {label: "문장", name: "item", widget: "string"} }
          - { label: "주소", name: "contact.address", widget: "string" }
          - { label: "대표번호", name: "contact.tel", widget: "string" }
          - { label: "이메일", name: "contact.email", widget: "string" }
          - { label: "사업자등록번호", name: "contact.regno", widget: "string" }
